services:
  php-apache:
    build: .
    ports:
      - "8045:80"  # Mapeia a porta 80 do contêiner para a porta 8080 do host
    volumes:
      - ./src:/var/www/html  # Sincroniza o código do host com o contêiner
