services:
  php-apache:
    build: .
    ports:
      - "8045:80" 
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=vini
      - DATABASE_PASSWORD=batata

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: vini
      POSTGRES_PASSWORD: batata
    ports:
      - "5442:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vini@teste.com  # Email padrão para login no pgAdmin
      PGADMIN_DEFAULT_PASSWORD: batata  # Senha padrão para login no pgAdmin
    ports:
      - "5050:80"  # Mapeia a porta 80 do pgAdmin para a porta 5050 do host
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:

