services:
  php-apache:
    build: .
    ports:
      - "8080:80" 
    volumes:
      - ./src:/var/www/back
    depends_on:
      - db
    environment:
      - DATABASE_HOST=192.168.15.167
      - DATABASE_PORT=5442
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vini@teste.com  # Email padrão para login no pgAdmin
      PGADMIN_DEFAULT_PASSWORD: postgres  # Senha padrão para login no pgAdmin
    ports:
      - "5050:80"  # Mapeia a porta 80 do pgAdmin para a porta 5050 do host
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:

